steps:
  # # Install npm dependencies
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['install']
  #   dir: src
  # # Run tests
  # - name: 'gcr.io/cloud-builders/npm'
  #   args: ['test']
  #   dir: src
  # Build the container image WITHOUT CACHE
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'eu.gcr.io/$PROJECT_ID/run-demo:$SHORT_SHA', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/run-demo:$SHORT_SHA']
  # Deploy to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'deploy-demo'
    - '--project'
    - '$_DEPLOY_PROJECT'
    - '--image'
    - 'eu.gcr.io/$PROJECT_ID/run-demo:$SHORT_SHA'
    - '--region'
    - '$_RUN_REGION'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    env:
      - '_DEPLOY_PROJECT=$_DEPLOY_PROJECT'
      - '_RUN_REGION=$_RUN_REGION'
