steps:
  # Build and Push container with Kaniko executor
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=eu.gcr.io/$PROJECT_ID/cloud-build-std
      - --cache=true
      - --cache-ttl=1h
